[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "geopyv"
version = "0.0.34"
authors = [
  { name="Sam Stanier", email="sas229@cam.ac.uk" },
  { name="Jonathan Smith", email="jdks2@cam.ac.uk" },
]
description = "A PIV/DIC analysis package for Python."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]

[tool.setuptools.package_data]
"geopyv" = ["README.md", "LICENSE", "basictest.py"]

dependencies = [
    "gmsh",
    "scipy",
    "opencv-contrib-python",
    "pyside6",
    "alive-progress",
    "pandas",
    "seaborn",
    "shapely",
    "numpy",
    "matplotlib",
    # "geomat"
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "sphinxcontrib-bibtex",
    "sphinx-autoapi",
    "sphinx-copybutton",
    "sphinx",
    "sphinx-rtd-theme",
    "pre-commit",
    "pytest",
    "flake8",
    "black",
    "flake8-black"
]

[tool.scikit-build]
minimum-version = "0.5"

[tool.scikit-build.wheel]
packages = ["geopyv"]
cmake = true

[tool.scikit-build.sdist]
include = [
    "basictest.py"
]